[package]
name = "vertigo-cmark"
version = "0.1.0"
authors = ["Michał Pokrywka <wolfmoon@o2.pl>"]
description = "Allows to render CommonMark inside Vertigo tree"
readme = "README.md"
keywords = ["wasm", "web", "reactive", "markdown", "commonmark"]
homepage = "https://vertigo.znoj.pl"
repository = "https://github.com/vertigo-web/vertigo-cmark"
documentation = "https://docs.rs/vertigo-cmark/"
categories = ["asynchronous", "gui", "wasm", "web-programming"]
license = "MIT OR Apache-2.0"
edition = "2024"

[features]
default = ["html"]
html = ["html5tokenizer"]

[dependencies]
syntect = { version = "5.2", default-features = false, features = ["default-fancy"], optional = true }
pulldown-cmark = "0.13"
vertigo = ">=0.7"
html5tokenizer = { version = "0.5", optional = true }
