use vertigo::Css;

#[derive(Clone)]
pub struct CMarkStyle {
    pub blockquote: Css,
    pub codeblock: Css,
    pub container: Css,
    pub dd: Css,
    pub del: Css,
    pub dl: Css,
    pub dt: Css,
    pub em: Css,
    pub h1: Css,
    pub h2: Css,
    pub h3: Css,
    pub h4: Css,
    pub h5: Css,
    pub h6: Css,
    pub img: Css,
    pub li: Css,
    pub a: Css,
    pub ol: Css,
    pub p: Css,
    pub strong: Css,
    pub sub: Css,
    pub sup: Css,
    pub table: Css,
    pub tbody: Css,
    pub td: Css,
    pub th: Css,
    pub thead: Css,
    pub tr: Css,
    pub ul: Css,
}

impl Default for CMarkStyle {
    fn default() -> Self {
        Self {
            blockquote: Css::default(),
            codeblock: Css::default(),
            container: Css::default(),
            dd: Css::default(),
            del: Css::default(),
            dl: Css::default(),
            dt: Css::default(),
            em: Css::default(),
            h1: Css::default(),
            h2: Css::default(),
            h3: Css::default(),
            h4: Css::default(),
            h5: Css::default(),
            h6: Css::default(),
            img: Css::default(),
            li: Css::default(),
            a: Css::default(),
            ol: Css::default(),
            p: Css::default(),
            strong: Css::default(),
            sub: Css::default(),
            sup: Css::default(),
            table: Css::str("border: 1"),
            tbody: Css::default(),
            td: Css::default(),
            th: Css::default(),
            thead: Css::default(),
            tr: Css::default(),
            ul: Css::default(),
        }
    }
}
